### ISSUE TITLE
CircleCI自动化部署静态资源

### ISSUE THREAD

**Issue by xuya227939** [xuya227939/blog#68]
## 启动存储库
![image](https://user-images.githubusercontent.com/16217324/60810692-3bc3ef00-a1c0-11e9-8fe2-1791461eb52b.png)
## 编写config.yml
项目根目录下新建.circleci目录，新增config.yml配置文件
复制，粘贴。以下配置项，请参考官方文档。[传送门](https://circleci.com/docs/)
```
version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: sudo npm install -g npm@6
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run build
      - run: echo '部署开始'
      - run: sudo apt-get update && sudo apt-get install rsync
      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - add_ssh_keys:
          fingerprints:
            - "bd:dd:23:90:d7:86:80:d8:92:31:1b:41:09:09:27:87"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              rsync -avce ssh build $SSH_USER@$SSH_IP:/data/corki-ui-web/
            else
              echo "Not master branch, dry run only"
            fi
      - run: echo '部署完毕'
workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
```
代码流程：
- 安装特定版本npm```sudo npm install -g npm@6```
- 安装npm包```npm install```
- 缓存文件```save_cache```
- 打包```npm run build ```
- 安装传输命令```sudo apt-get update && sudo apt-get install rsync```
- 恢复缓存key```restore_cache```，需先缓存
- 添加ssh密钥```add_ssh_keys```
- 推送文件到服务器```deploy```
## 添加ssh密钥
登录服务器
```cd ~/.ssh/```
```ssh-keygen -t rsa ```创建公钥(.pub)和私钥
```cat id_rsa```
复制私钥所有内容，粘贴到输入框里面，填上名称

![image](https://user-images.githubusercontent.com/16217324/60812544-56986280-a1c4-11e9-97b4-02eb7e96c4df.png)
要将此密钥导入CI环境，我们使用该add_ssh_keys步骤。添加SSH密钥后，CircleCI在设置屏幕上显示密钥的指纹。复制此指纹并将其插入上述命令，我们的构建环境现在可以使用该密钥。

要使CircleCI能够通过文件将文件发送到服务器rsync，请单击“ 构建”屏幕上项目名称旁边的cog来访问项目的构建设置。在设置屏幕上，找到权限部分下的SSH权限链接。单击“ 添加SSH密钥”按钮，然后添加服务器的主机名和私钥的内容

## 提供Hostkey进行验证
当CircleCI服务器尝试连接到您的主机时，它可能会提示您验证主机密钥。提示是自动化的氪星石：CI环境将无限期挂起，等待用户给出响应。可以禁用此验证，但将正确的密钥添加到known_hosts文件是一个更好的解决方案。CircleCI没有用于添加主机密钥的语义解决方案，但一种选择是将主机密钥添加为环境变量。要添加环境变量，请转到项目设置，然后单击“ 构建设置”下的“ 环境变量”链接。单击“ 添加变量”按钮，然后添加一个以REMOTE_HOSTKEY服务器主机密钥内容命名的新值。要获取主机密钥，请在终端中运行以下
![image](https://user-images.githubusercontent.com/16217324/60812650-95c6b380-a1c4-11e9-8591-e1250f758903.png)

然后新建环境变量
![image](https://user-images.githubusercontent.com/16217324/60812696-b0009180-a1c4-11e9-8067-cca84df9046f.png)
![image](https://user-images.githubusercontent.com/16217324/60812769-d7575e80-a1c4-11e9-82ed-112f4bccb030.png)
## 部署命令
```
- deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              rsync -avce ssh build $SSH_USER@$SSH_IP:/data/corki-ui-web/
            else
              echo "Not master branch, dry run only"
            fi
```
针对master分支进行发布
- $SSH_USER 环境变量，服务器用户名
- $SSH_IP 环境变量，服务器ip
这里选择你要部署的项目
![image](https://user-images.githubusercontent.com/16217324/60810768-6a41ca00-a1c0-11e9-8082-54cd8668a226.png)
- 选择环境
- 选择docker镜像(这里以node为例)
- 开始构建
